plaza kullanıcı örneği 2 layoutlu/TVapimvcuygulama/mvckatmani/Controllers/BlokAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvckatmani.Models;
using System.Net.Http;

namespace mvckatmani.Controllers
{
    public class BlokAdminController : Controller
    {
        // GET: BlokAdmin
        public ActionResult Index()
        {
            IEnumerable<mvcBlokModel> listele;
            HttpResponseMessage response = BlokAdmin.webapiclient.GetAsync("Bloklars").Result;
            listele = response.Content.ReadAsAsync<IEnumerable<mvcBlokModel>>().Result;
            return View(listele);
     
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View(new mvcBlokModel());
            }
            else
            {
                HttpResponseMessage response = BlokAdmin.webapiclient.GetAsync("Bloklars/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcBlokModel>().Result);
            }

        }
        [HttpPost]
        public ActionResult EY(mvcBlokModel blok)
        {
            if (blok.BlokNo == 0)
            {
                HttpResponseMessage response = BlokAdmin.webapiclient.PostAsJsonAsync("Bloklars", blok).Result;
            }
            else
            {
                HttpResponseMessage response = BlokAdmin.webapiclient.PutAsJsonAsync("Bloklars/" + blok.BlokNo, blok).Result;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = BlokAdmin.webapiclient.DeleteAsync("Bloklars/" + id.ToString()).Result;
            return RedirectToAction("Index");

        }
    }
}

plaza kullanıcı örneği 2 layoutlu/TVapimvcuygulama/mvckatmani/Controllers/GorevAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvckatmani.Models;
using System.Net.Http;

namespace mvckatmani.Controllers
{
    public class GorevAdminController : Controller
    {
        // GET: GorevAdmin
        public ActionResult Index()
        {
                IEnumerable<mvcGorevModel> listele;
                HttpResponseMessage response = Gorev.webapiclient.GetAsync("Görevlers").Result;
                listele = response.Content.ReadAsAsync<IEnumerable<mvcGorevModel>>().Result;
                return View(listele);
            
        }
    }
}

plaza kullanıcı örneği 2 layoutlu/TVapimvcuygulama/mvckatmani/Controllers/HizmetAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvckatmani.Models;
using System.Net.Http;

namespace mvckatmani.Controllers
{
    public class HizmetAdminController : Controller
    {
        // GET: HizmetAdmin
        public ActionResult Index()
        {
            IEnumerable<mvcHizmetModel> listele;
            HttpResponseMessage response = Hizmet.webapiclient.GetAsync("Hizmetlers").Result;
            listele = response.Content.ReadAsAsync<IEnumerable<mvcHizmetModel>>().Result;
            return View(listele);
        }
    }
}

plaza kullanıcı örneği 2 layoutlu/TVapimvcuygulama/mvckatmani/Controllers/PlazaAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvckatmani.Models;
using System.Net.Http;

namespace mvckatmani.Controllers
{
    public class PlazaAdminController : Controller
    {
        // GET: PlazaAdmin
        public ActionResult Index()
        {

            IEnumerable<mvcPlazaModel> listele;
            HttpResponseMessage response = PlazaAdmin.webapiclient.GetAsync("Plazalars").Result;
            listele = response.Content.ReadAsAsync<IEnumerable<mvcPlazaModel>>().Result;
            return View(listele);
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View(new mvcPlazaModel());
            }
            else
            {
                HttpResponseMessage response = PlazaAdmin.webapiclient.GetAsync("Plazalars/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<mvcPlazaModel>().Result);
            }

        }
        [HttpPost]
        public ActionResult EY(mvcPlazaModel plaza)
        {
            if (plaza.PlazaNo == 0)
            {
                HttpResponseMessage response = PlazaAdmin.webapiclient.PostAsJsonAsync("Plazalars", plaza).Result;
            }
            else
            {
                HttpResponseMessage response = PlazaAdmin.webapiclient.PutAsJsonAsync("Plazalars/" + plaza.PlazaNo, plaza).Result;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = PlazaAdmin.webapiclient.DeleteAsync("Plazalars/" + id.ToString()).Result;
            return RedirectToAction("Index");
        }

        }
    }

plaza kullanıcı örneği 2 layoutlu/TVapimvcuygulama/mvckatmani/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Plaza Dünyası", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Plazalar", "Index", "PlazaAdmin")</li>
                    <li>@Html.ActionLink("Bloklar", "Index", "BlokAdmin")</li>
                    <li>@Html.ActionLink("Görevler", "Index", "GorevAdmin")</li>
                    <li>@Html.ActionLink("Hizmetler", "Index", "HizmetAdmin")</li>
                    <li>@Html.ActionLink("Personeller", "Index", "PersonelAdmin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>